### PR TITLE
Fixes #907 more robust highlight process should not crash

### LINKED ISSUE #907: population/parallelComparison workflow: the new logging crashes in the PlotTimeProfiles task
Got the error message below for one workflow. 
```
i Info	Starting run of Plot Time profiles and Residuals task for PO450mg
Error: Error in gsub(pattern = highlightWrap[1], x = as.character(text), replacement = "", : input string 1 is invalid UTF-8
```
Unfortunately I cannot upload the workflow inputs here. IT is population/parallelComparison workflow.
The error must come from 
https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/blob/1a0c1e46f0ebf6cf9a52b0bbaf0e5da545bb127d/R/messages.R#L310

### PR DESCRIPTION
**Pull request by pchelle**

### CODE REVIEW

File: R/messages.R [hunk 1]
```diff
@@ -302,14 +302,39 @@ highlight <- function(text) {
...
-    highlightWrap <- strsplit(highlight(" "), split = " ")[[1]]
-    if(!isOfLength(highlightWrap,2)){
+  if (!requireNamespace("crayon", quietly = TRUE)) {
+    return(text)
+  }
+  # Hard coding results of
+  # strsplit(highlight(" "), split = " ")[[1]]
+  # to prevent any bug from highlight and strsplit
+  highlightLeft <- "\033[36m\033[1m\033[3m"
+  highlightRight <- "\033[23m\033[22m\033[39m"
```
Comment (Yuri05) [inline R/messages.R:312]: crazy
