### PR TITLE
Fixes #190 validate that file exists before loading it

### LINKED ISSUE #190: Pop simulation: unclear error message if simulation does not exist
In the example attached invalid simulation file name was set.
The error message is unclear.

[04_InvalidSim.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/4643588/04_InvalidSim.zip)

```
[1] "18/05/2020 - 12:46:28 : Run simulation: NONEXISTING"
[1] "18/05/2020 - 12:46:28 : Starting parallel population simulation"
        2 slaves are spawned successfully. 0 failed.
master (rank 0, comm 1) of size 3 is running on: XXX
slave1 (rank 1, comm 1) of size 3 is running on: XXX
slave2 (rank 2, comm 1) of size 3 is running on: XXX
[1] "18/05/2020 - 12:46:32 : ospsuite.reportingengine loaded successfully on all cores"
[1] "18/05/2020 - 12:46:33 : ospsuite loaded successfully on all cores"
Error in if (success) { : missing value where TRUE/FALSE needed
In addition: Warning message:
In all(allCoreResults) : coercing argument of type 'character' to logical
```

### PR DESCRIPTION
**Pull request by pchelle**

### CODE REVIEW

File: R/simulation-set.R [hunk 1]
```diff
@@ -68,6 +68,8 @@ SimulationSet <- R6::R6Class(
       # but not here as it would mean that nothing would be reported
       validateIsIncluded(c(applicationRanges), ApplicationRanges)
 
+      # Before loading the simulation, check if the file exists
+      validateFileExists(simulationFile)
```
Comment (Yuri05) [inline R/simulation-set.R:72]: makes sense :)

**Review by Yuri05 — APPROVED** [review]
